namespace MyProject.lib {
    using Microsoft.AspNetCore.Components.Forms;
    using NLog;
    using System.Security.Cryptography;
    using System.Text;

    public static class FileCryptoTool {
        private const string MAGIC_HEADER = "mKtjErRy";
        private const int HeaderSize = 8;
        private const int SaltSize = 32;
        private const int HmacSize = 32;
        private const int Iterations = 50000;

        public static bool EncryptFile(string inputPath, string outputPath, string password, out string err) {
            err = "";
            if (!File.Exists(inputPath)) {
                err = $"inputFile({inputPath}) not exists";
                return false;
            }

            if (!CheckFileNameValidChar(outputPath)) {
                err = $"outputFile({outputPath}) 檔名有不合法的字元";
                return false;
            }
            var path = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(path) && !Path.Exists(path)) {
                ForceCreateFolder(path);
            }

            try {
                byte[] salt = GenerateSalt();
                byte[] passwordBytes = Encoding.UTF8.GetBytes(password);

                using var keyGen = new Rfc2898DeriveBytes(passwordBytes, salt, Iterations, HashAlgorithmName.SHA256);
                using var aes = Aes.Create();
                aes.KeySize = 256;
                aes.BlockSize = 128;
                aes.Mode = CipherMode.CFB;
                aes.Padding = PaddingMode.PKCS7;

                aes.Key = keyGen.GetBytes(32);
                aes.IV = keyGen.GetBytes(16);

                using var fsIn = new FileStream(inputPath, FileMode.Open, FileAccess.Read);
                using var msEncrypted = new MemoryStream();
                using (var cryptoStream = new CryptoStream(msEncrypted, aes.CreateEncryptor(), CryptoStreamMode.Write)) {
                    fsIn.CopyTo(cryptoStream);
                }
                byte[] encryptedData = msEncrypted.ToArray();

                using var hmac = new HMACSHA256(aes.Key);
                byte[] hmacHash = hmac.ComputeHash(encryptedData);

                using var fsOut = new FileStream(outputPath, FileMode.Create, FileAccess.Write);
                fsOut.Write(Encoding.ASCII.GetBytes(MAGIC_HEADER));  // Magic Header (8)
                fsOut.Write(salt);                                   // Salt (32)
                fsOut.Write(hmacHash);                               // HMAC (32)
                fsOut.Write(encryptedData);                          // Encrypted data
            }
            catch (Exception ex) {
                err = $"Encryption failed: {ex.Message}";
                return false;
            }

            return true;
        }

        public static bool DecryptFile(string inputPath, string outputPath, string password, out string err) {
            err = "";
            if (!File.Exists(inputPath)) {
                err = $"inputFile({inputPath}) not exists";
                return false;
            }

            if (!CheckFileNameValidChar(outputPath)) {
                err = $"outputFile({outputPath}) 檔名有不合法的字元";
                return false;
            }

            var path = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(path) && !Path.Exists(path)) {
                ForceCreateFolder(path);
            }

            try {
                byte[] allBytes = File.ReadAllBytes(inputPath);

                if (allBytes.Length < HeaderSize + SaltSize + HmacSize) {
                    err = "Encrypted file too small.";
                    return false;
                }

                // Parse
                string magic = Encoding.ASCII.GetString(allBytes[..HeaderSize]);
                if (magic != MAGIC_HEADER) {
                    err = "Invalid magic header. Not generated by SIPRecorder";
                    return false;
                }

                byte[] salt = allBytes.AsSpan(HeaderSize, SaltSize).ToArray();
                byte[] hmacStored = allBytes.AsSpan(HeaderSize + SaltSize, HmacSize).ToArray();
                byte[] encryptedData = allBytes[(HeaderSize + SaltSize + HmacSize)..];

                byte[] passwordBytes = Encoding.UTF8.GetBytes(password);
                using var keyGen = new Rfc2898DeriveBytes(passwordBytes, salt, Iterations, HashAlgorithmName.SHA256);
                byte[] key = keyGen.GetBytes(32);
                byte[] iv = keyGen.GetBytes(16);

                // 驗證 HMAC
                using var hmac = new HMACSHA256(key);
                byte[] hmacComputed = hmac.ComputeHash(encryptedData);
                if (!hmacStored.SequenceEqual(hmacComputed)) {
                    err = "HMAC validation failed. Wrong password or file tampered.";
                    return false;
                }

                using var aes = Aes.Create();
                aes.KeySize = 256;
                aes.BlockSize = 128;
                aes.Mode = CipherMode.CFB;
                aes.Padding = PaddingMode.PKCS7;
                aes.Key = key;
                aes.IV = iv;

                using var msEncrypted = new MemoryStream(encryptedData);
                using var cryptoStream = new CryptoStream(msEncrypted, aes.CreateDecryptor(), CryptoStreamMode.Read);
                using var fsOut = new FileStream(outputPath, FileMode.Create, FileAccess.Write);
                cryptoStream.CopyTo(fsOut);
            }
            catch (Exception ex) {
                err = $"Decryption failed: {ex.Message}";
                return false;
            }

            return true;
        }

        private static void SafeDelete(string? path) {
            try {
                if (!string.IsNullOrEmpty(path) && File.Exists(path))
                    File.Delete(path);
            }
            catch {
                // 刪除失敗不拋出，避免遮蔽主要錯誤
            }
        }

        /// <summary>
        /// 解密到暫存檔。成功回傳 true 並提供 tempPath；失敗回傳 false 並提供錯誤訊息。
        /// </summary>
        private static bool DecryptToTempFile(string inputPath, out string tempPath, string password, out string error) {
            tempPath = "";
            error = string.Empty;

            try {
                var tempName = Path.GetRandomFileName() + Path.GetExtension(inputPath);
                tempPath = Path.Combine(Path.GetTempPath(), tempName);

                var ok = DecryptFile(inputPath, tempPath, password, out error);
                if (!ok) {
                    SafeDelete(tempPath);
                    tempPath = string.Empty;                     
                    return false;
                }

                if (!File.Exists(tempPath)) {
                    error = "解密後的暫存檔不存在。";
                    return false;
                }

                return true;
            }
            catch (Exception ex) {
                SafeDelete(tempPath);
                tempPath = string.Empty;
                error = $"解密過程發生例外：{ex.Message}";
                return false;
            }
        }


        private static byte[] GenerateSalt() {
            byte[] salt = new byte[SaltSize];
            RandomNumberGenerator.Fill(salt);
            return salt;
        }

        public static bool CheckFileNameValidChar(string fullFileName) {

            // 檢查 PATH
            var invalidPathChar = Path.GetInvalidPathChars();
            var path = Path.GetDirectoryName(fullFileName);
            if (string.IsNullOrEmpty(path))
                return true;
            if (path.IndexOfAny(invalidPathChar) >= 0)
                return false;
            // 檢查 file name
            var invalidFileChar = Path.GetInvalidFileNameChars();
            var fileName = Path.GetFileName(fullFileName);
            if (string.IsNullOrEmpty(fileName))
                return true;
            if (fileName.IndexOfAny(invalidFileChar) >= 0)
                return false;
            //
            return true;
        }

        public static async Task<(bool Result, string ErrorMsg)> EncryptAndCleanupAsync(string inputFile, string outputFile, string password, bool deleteSource = true) {
            var errEnc = "";
            var errMsg = "";
            // 呼叫加密
            bool encryptOk = await Task.Run(() =>
                EncryptFile(inputFile, outputFile, password, out errEnc)
            );

            if (!encryptOk) {
                errMsg = $"加密失敗: {inputFile} → {outputFile}, 錯誤: {errEnc}";
                return (false, errMsg);
            }

            // 加密成功後，立即嘗試解密驗證
            string verifyPath = Path.GetTempFileName();
            bool verifyOk = await Task.Run(() =>
                DecryptFile(outputFile, verifyPath, password, out var verifyErr)
            );

            try {
                File.Delete(verifyPath);
                if (verifyOk) {                    
                    if (deleteSource) {
                        File.Delete(inputFile);
                        errMsg = $"加密並驗證成功，已刪除原始檔案: {inputFile}"; 
                    }
                    else {
                        errMsg = $"加密並驗證成功, 保留原始檔案: {inputFile}";
                    }
                    return (true, errMsg);
                }
                else {
                    errMsg = $"驗證加密檔案失敗: {outputFile}，保留原始檔案";
                    return (false, errMsg);
                }
            }
            catch (Exception ex) {
                errMsg = $"處理驗證或刪除時發生錯誤: {ex.Message}, inputFile={inputFile}";
                return (false, errMsg);
            }
        }

        


        /// <summary>
        /// 檢查是否為新版加密格式（含 magic header）
        /// </summary>
        public static bool IsNewEncryptedFormat(string filePath) {
            if (!File.Exists(filePath))
                return false;

            try {
                // 允許其他程式存取中也能開啟
                using var fs = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite | FileShare.Delete );

                if (fs.Length < 8) 
                    return false;

                byte[] header = new byte[8];
                fs.Read(header, 0, 8);
                string headerStr = Encoding.ASCII.GetString(header);

                return headerStr == MAGIC_HEADER;
            }
            catch {
                return false; // 讀取失敗則當作不是新格式
            }
        }

        /// <summary>
        /// 解密之前舊的錄音檔
        /// </summary>
        /// <param name="inputFile"></param>
        /// <param name="outputFile"></param>
        /// <param name="err"></param>
        /// <returns></returns>
        public static bool DecryptOldFormat(string inputFile, string outputFile, out string err) {
            err = "";
            if (!File.Exists(inputFile)) {
                err = $"inputFile({inputFile}) not exists";
                return false;
            }

            if (!CheckFileNameValidChar(outputFile)) {
                err = $"outputFile({outputFile}) 檔名有不合法的字元";
                return false;
            }
            
            var path = Path.GetDirectoryName(outputFile);
            if (!string.IsNullOrEmpty(path) && !Path.Exists(path) ) {
                ForceCreateFolder(path);                
            }

            try {
                byte[] cipher = File.ReadAllBytes(inputFile);
                using var aes = Aes.Create();
                aes.Key = Encoding.UTF8.GetBytes("095550212309556839030911663903MW");
                aes.IV = Encoding.UTF8.GetBytes("0492721473mktwen");
                aes.Mode = CipherMode.CFB;
                aes.Padding = PaddingMode.PKCS7;

                using var ms = new MemoryStream(cipher);
                using var crypto = new CryptoStream(ms, aes.CreateDecryptor(), CryptoStreamMode.Read);
                using var fsOut = new FileStream(outputFile, FileMode.Create);
                crypto.CopyTo(fsOut);
            }
            catch (Exception ex) {
                err = "舊格式解密失敗: " + ex.Message;
                return false;
            }

            return true;
        }

        public static string ForceCreateFolder(string path) {
            var err = "";
            if (Directory.Exists(path))
                return err;
            try {
                Directory.CreateDirectory(path);
            }
            catch (Exception ex) {
                err = ex.Message;
            }
            return err;
        }

        /// <summary>
        /// 嘗試取得可讀取的 FileStream。
        /// 規則：
        /// 1) 檢查檔案是否存在；不存在回傳 null，並填入錯誤訊息。
        /// 2) 若 IsNewEncryptedFormat(filePath) 為 true，先解密到暫存檔，再以 DeleteOnClose 開啟串流。
        /// 3) 非加密則直接開啟原檔案（Read / Share ReadWrite|Delete）。
        /// 4) 任何例外都回傳 null，並在 error 填入原因。
        /// </summary>
        public static FileStream? GetFileStream(string inputFile, out string finalOutput, out bool excrypted, string password, out string error) {
            error = string.Empty;
            finalOutput = inputFile;
            excrypted = false;
            if (string.IsNullOrWhiteSpace(inputFile)) {
                error = "filePath 不能為空白。";
                return null;
            }

            try {
                if (!File.Exists(inputFile)) {
                    error = $"檔案不存在：{inputFile}";
                    return null;
                }

                // 需要解密？
                if (IsNewEncryptedFormat(inputFile)) {
                    excrypted = true;                    
                    if (!DecryptToTempFile(inputFile, out finalOutput, password, out error)) {                        
                        return null;
                    }

                    // 用 DeleteOnClose，確保串流關閉即刪除暫存明文
                    return new FileStream(
                        finalOutput!,
                        new FileStreamOptions {
                            Mode = FileMode.Open,
                            Access = FileAccess.Read,
                            Share = FileShare.ReadWrite | FileShare.Delete,
                            Options = FileOptions.SequentialScan | FileOptions.Asynchronous | FileOptions.DeleteOnClose
                        });
                }
                else {
                    // 非加密，直接開啟原檔案
                    return new FileStream(
                        inputFile,
                        new FileStreamOptions {
                            Mode = FileMode.Open,
                            Access = FileAccess.Read,
                            Share = FileShare.ReadWrite | FileShare.Delete,
                            Options = FileOptions.SequentialScan | FileOptions.Asynchronous
                        });
                }
            }
            catch (UnauthorizedAccessException ex) {
                error = $"存取被拒：{ex.Message}";
                return null;
            }
            catch (IOException ex) {
                // 常見：檔案被占用、I/O 裝置錯誤、路徑或分享模式衝突
                error = $"I/O 錯誤：{ex.Message}";
                return null;
            }
            catch (Exception ex) {
                error = $"未預期的錯誤：{ex.Message}";
                return null;
            }
        }
    }


}
